openapi: 3.1.0
x-stoplight:
  id: urg0echx27xpf
info:
  title: OpenWeatherMap API
  version: '2.5'
  contact:
    name: Support
    url: 'https://openweathermap.org/api'
    email: ashleysally@gmail.com
  summary: Get the current weather
  description: 'Get the current weather, daily forecast for 16 days, and a three-hour-interval forecast for 5 days for your city. Helpful stats, graphics, and this day in history charts are available for your reference. Interactive maps show precipitation, clouds, pressure, wind around your location stations. Data is available in JSON, XML, or HTML format. **Note**: This sample Swagger file covers the `current` endpoint only from the OpenWeatherMap API. <br/><br/> **Note**: All parameters are optional, but you must select at least one parameter. Calling the API by city ID (using the `id` parameter) will provide the most precise location results.'
  termsOfService: 'https://openweathermap.org/terms'
  license:
    name: Attribution-ShareAlike 4.0 International (CC BY-SA 4.0)
    url: 'https://creativecommons.org/licenses/by-sa/4.0/'
servers:
  - url: 'https://api.openweathermap.org/data/2.5'
    description: prod
paths:
  /weather:
    get:
      summary: Call current weather data for one loacation
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
                x-examples:
                  Example 1:
                    coord:
                      lon: -121.95
                      lat: 37.35
                    weather:
                      - id: 803
                        main: Clouds
                        description: broken clouds
                        icon: 04n
                    base: stations
                    main:
                      temp: 45.25
                      feels_like: 41.16
                      temp_min: 41
                      temp_max: 50
                      pressure: 1026
                      humidity: 75
                    visibility: 16093
                    wind:
                      speed: 2.57
                      deg: 36
                    clouds:
                      all: 75
                    dt: 1579415808
                    sys:
                      type: 1
                      id: 5845
                      country: US
                      sunrise: 1579360793
                      sunset: 1579396557
                    timezone: -28800
                    id: 0
                    name: Santa Clara
                    cod: 200
                properties:
                  coord:
                    type: object
                    properties:
                      lon:
                        type: number
                        description: 'City geo location, longitude'
                      lat:
                        type: number
                        description: 'City geo location, latitude'
                  weather:
                    type: array
                    items:
                      type: object
                      properties:
                        id:
                          type: integer
                          description: 'description: Weather condition id'
                        main:
                          type: string
                          description: 'Group of weather parameters (Rain, Snow, Extreme etc.)'
                        description:
                          type: string
                          description: Weather condition within the group
                        description - copy:
                          type: string
                          description: Weather condition within the group
                        icon:
                          type: string
                          description: 'description: '
                  base:
                    type: string
                    description: Internal parameter
                  main:
                    type: object
                    properties:
                      temp:
                        type: number
                        description: 'Temperature. Unit Default: Kelvin, Metric: Celsius, Imperial: Fahrenheit'
                      feels_like:
                        type: number
                        description: What the weather feels like despite the actual numbers
                      temp_min:
                        type: integer
                        description: 'Minimum temperature at the moment. This is deviation from current temp that is possible for large cities and megalopolises geographically expanded (use these parameter optionally). Unit Default: Kelvin, Metric: Celsius, Imperial: Fahrenheit'
                      temp_max:
                        type: integer
                        description: 'Maximum temperature at the moment. This is deviation from current temp that is possible for large cities and megalopolises geographically expanded (use these parameter optionally). Unit Default: Kelvin, Metric: Celsius, Imperial: Fahrenheit'
                      pressure:
                        type: integer
                        description: 'Atmospheric pressure (on the sea level, if there is no sea_level or grnd_level data), hPa'
                      humidity:
                        type: integer
                        description: 'Humidity, %'
                  visibility:
                    type: integer
                    description: 'Visibility, meter'
                  wind:
                    type: object
                    description: 'Wind speed. Unit Default: meter/sec, Metric: meter/sec, Imperial: miles/hour'
                    properties:
                      speed:
                        type: number
                      deg:
                        type: integer
                        description: |
                          ‘’
                  clouds:
                    type: object
                    description: 'Cloudiness, %'
                    properties:
                      all:
                        type: integer
                  dt:
                    type: integer
                    description: 'Time of data calculation, unix, UTC'
                  sys:
                    type: object
                    description: Internal parameter
                    properties:
                      type:
                        type: integer
                      id:
                        type: integer
                        description: |
                          Internal parameter
                      country:
                        type: string
                        description: 'Country code (GB, JP etc.'
                      sunrise:
                        type: integer
                        description: 'Sunrise time, unix, UTC'
                      sunset:
                        type: integer
                        description: 'Sunset time, unix, UTC'
                  timezone:
                    type: integer
                    description: the timezone for the station
                  id:
                    type: integer
                    description: City ID
                  name:
                    type: string
                    description: 'description: '
                  cod:
                    type: integer
                    description: 'description: '
              examples:
                Example 1:
                  value:
                    coord:
                      lon: 0
                      lat: 0
                    weather:
                      - id: 0
                        main: string
                        description: string
                        icon: string
                    base: string
                    main:
                      temp: 0
                      feels_like: 0
                      temp_min: 0
                      temp_max: 0
                      pressure: 0
                      humidity: 0
                    visibility: 0
                    wind:
                      speed: 0
                      deg: 0
                    clouds:
                      all: 0
                    dt: 0
                    sys:
                      type: 0
                      id: 0
                      country: string
                      sunrise: 0
                      sunset: 0
                    timezone: 0
                    id: 0
                    name: string
                    cod: 0
      operationId: get-weather
      description: 'Access current weather data for any location on Earth including over 200,000 cities! Current weather is frequently updated based on global models and data from more than 40,000 weather station'
      parameters:
        - schema:
            type: string
            enum:
              - standard
              - metric
              - imperial
          in: query
          name: zip
          description: '**Zip code**. Search by zip code. *Example: 95050,us*. Please note that if the country is not specified, the search uses USA as a default.'
        - schema:
            type: string
          in: query
          name: units
          description: '**Units**. *Example: imperial*. Possible values: `standard`, `metric`, and `imperial`. When you do not use the `units` parameter, the format is `standard` by default.'
        - schema:
            type: string
          in: query
          name: q
          description: '**City name**. *Example: London*. You can call by city name, or by city name and country code. The API responds with a list of results that match a searching word. For the query value, type the city name and optionally the country code divided by a comma; use ISO 3166 country codes.'
        - schema:
            type: string
          in: query
          name: id
          description: '**City ID**. *Example: `2172797`*. You can call by city ID. The API responds with the exact result. The List of city IDs can be downloaded [here](http://bulk.openweathermap.org/sample/). You can include multiple cities in this parameter — just separate them by commas. The limit of locations is 20. *Note: A single ID counts as a one API call. So, if you have city IDs, it’s treated as 3 API calls.*'
        - $ref: '#/components/parameters/Ion'
        - schema:
            type: string
            default: en
            enum:
              - ar
              - bg
              - ca
              - cz
              - de
              - el
              - en
              - fa
              - fi
              - fr
              - gl
              - hr
              - hu
              - it
              - ja
              - kr
              - la
              - lt
              - mk
              - nl
              - pl
              - pt
              - ro
              - ru
              - se
              - sk
              - sl
              - es
              - tr
              - ua
              - vi
              - zh_cn
              - zh_tw
          in: query
          name: lang
          description: '**Language**. *Example: en*. You can use `lang` parameter to get the output in your language. We support the following languages that you can use with the corresponded lang values: Arabic - `ar`, Bulgarian - `bg`, Catalan - `ca`, Czech - `cz`, German - `de`, Greek - `el`, English - `en`, Persian (Farsi) - `fa`, Finnish - `fi`, French - `fr`, Galician - `gl`, Croatian - `hr`, Hungarian - `hu`, Italian - `it`, Japanese - `ja`, Korean - `kr`, Latvian - `la`, Lithuanian - `lt`, Macedonian - `mk`, Dutch - `nl`, Polish - `pl`, Portuguese - `pt`, Romanian - `ro`, Russian - `ru`, Swedish - `se`, Slovak - `sk`, Slovenian - `sl`, Spanish - `es`, Turkish - `tr`, Ukrainian - `ua`, Vietnamese - `vi`, Chinese Simplified - `zh_cn`, Chinese Traditional - `zh_tw`.'
        - schema:
            type: string
            enum:
              - json
              - xml
              - html
          in: query
          name: mode
          description: '**Mode**. Example: html. Determines the format of the response. Possible values are `json`, `xml`, and `html`. If the mode parameter is empty, the format is `json` by default.'
        - schema:
            type: string
          in: header
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties: {}
components:
  schemas:
    User:
      title: User
      type: object
      description: ''
      examples:
        - id: 142
          firstName: Alice
          lastName: Smith
          email: alice.smith@gmail.com
          dateOfBirth: '1997-10-31'
          emailVerified: true
          signUpDate: '2019-08-24'
      properties:
        id:
          type: integer
          description: Unique identifier for the given user.
        firstName:
          type: string
        lastName:
          type: string
        email:
          type: string
          format: email
        dateOfBirth:
          type: string
          format: date
          example: '1997-10-31'
        emailVerified:
          type: boolean
          description: Set to true if the user's email has been verified.
        createDate:
          type: string
          format: date
          description: The date that the user was created.
      required:
        - id
        - firstName
        - lastName
        - email
        - emailVerified
  securitySchemes:
    app_id:
      name: appid
      type: apiKey
      in: query
  parameters:
    Ion:
      name: Ion
      in: query
      required: false
      schema:
        type: string
      description: '**Longitude**. *Example: 139*. Longitude coordinate of the location of your interest. Must use with `lat `.'
security:
  - app_id: []
